import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        black: "var(--colors-black)",
        white: "var(--colors-white)",
        brand: {
          50: "var(--colors-brand-50)",
          100: "var(--colors-brand-100)",
          200: "var(--colors-brand-200)",
          300: "var(--colors-brand-300)",
          400: "var(--colors-brand-400)",
          500: "var(--colors-brand-500)",
          600: "var(--colors-brand-600)",
          700: "var(--colors-brand-700)",
          800: "var(--colors-brand-800)",
          900: "var(--colors-brand-900)",
          a10: "var(--colors-brand-a10)",
        },
        sky: {
          50: "var(--colors-sky-50)",
          100: "var(--colors-sky-100)",
          200: "var(--colors-sky-200)",
          300: "var(--colors-sky-300)",
          400: "var(--colors-sky-400)",
          500: "var(--colors-sky-500)",
          600: "var(--colors-sky-600)",
          700: "var(--colors-sky-700)",
          800: "var(--colors-sky-800)",
          900: "var(--colors-sky-900)",
        },
        gray: {
          50: "var(--colors-gray-50)",
          100: "var(--colors-gray-100)",
          200: "var(--colors-gray-200)",
          300: "var(--colors-gray-300)",
          400: "var(--colors-gray-400)",
          500: "var(--colors-gray-500)",
          600: "var(--colors-gray-600)",
          700: "var(--colors-gray-700)",
          800: "var(--colors-gray-800)",
          900: "var(--colors-gray-900)",
          a10: "var(--colors-gray-a10)",
        },
        red: {
          50: "var(--colors-red-50)",
          100: "var(--colors-red-100)",
          200: "var(--colors-red-200)",
          300: "var(--colors-red-300)",
          400: "var(--colors-red-400)",
          500: "var(--colors-red-500)",
          600: "var(--colors-red-600)",
          700: "var(--colors-red-700)",
          800: "var(--colors-red-800)",
          900: "var(--colors-red-900)",
        },
        yellow: {
          50: "var(--colors-yellow-50)",
          100: "var(--colors-yellow-100)",
          200: "var(--colors-yellow-200)",
          300: "var(--colors-yellow-300)",
          400: "var(--colors-yellow-400)",
          500: "var(--colors-yellow-500)",
          600: "var(--colors-yellow-600)",
          700: "var(--colors-yellow-700)",
          800: "var(--colors-yellow-800)",
          900: "var(--colors-yellow-900)",
        },
        green: {
          50: "var(--colors-green-50)",
          100: "var(--colors-green-100)",
          200: "var(--colors-green-200)",
          300: "var(--colors-green-300)",
          400: "var(--colors-green-400)",
          500: "var(--colors-green-500)",
          600: "var(--colors-green-600)",
          700: "var(--colors-green-700)",
          800: "var(--colors-green-800)",
          900: "var(--colors-green-900)",
        },
        lime: {
          50: "var(--colors-lime-50)",
          100: "var(--colors-lime-100)",
          200: "var(--colors-lime-200)",
          300: "var(--colors-lime-300)",
          400: "var(--colors-lime-400)",
          500: "var(--colors-lime-500)",
          600: "var(--colors-lime-600)",
          700: "var(--colors-lime-700)",
          800: "var(--colors-lime-800)",
          900: "var(--colors-lime-900)",
        },
        blue: {
          50: "var(--colors-blue-50)",
          100: "var(--colors-blue-100)",
          200: "var(--colors-blue-200)",
          300: "var(--colors-blue-300)",
          400: "var(--colors-blue-400)",
          500: "var(--colors-blue-500)",
          600: "var(--colors-blue-600)",
          700: "var(--colors-blue-700)",
          800: "var(--colors-blue-800)",
          900: "var(--colors-blue-900)",
        },
      },
      fontFamily: {
        heading: "var(--font-archivo)",
        body: "var(--font-family-body)",
      },
      fontSize: {
        heading1: "var(--typography-heading-h1)",
        heading2: "var(--typography-heading-h2)",
        heading3: "var(--typography-heading-h3)",
        heading4: "var(--typography-heading-h4)",
        heading5: "var(--typography-heading-h5)",
        heading6: "var(--typography-heading-h6)",
        body1SemiBold: "var(--typography-body-body1-semi-bold)",
        body2Regular: "var(--typography-body-body2-regular)",
        body3SemiBold: "var(--typography-body-body3-semi-bold)",
        body3Regular: "var(--typography-body-body3-regular)",
        body4SemiBold: "var(--typography-body-body4-semi-bold)",
        body4Regular: "var(--typography-body-body4-regular)",
        body5Bold: "var(--typography-body-body5-bold)",
        body5Regular: "var(--typography-body-body5-regular)",
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config;
