const customPlugin = require("./tailwind-plugin");

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        black: "var(--colors-black)",
        brand: {
          primary: "var(--colors-brand-500)",
          subtle: "var(--colors-brand-50)",
          "50": "var(--colors-brand-50)",
          "100": "var(--colors-brand-100)",
          "200": "var(--colors-brand-200)",
          "300": "var(--colors-brand-300)",
          "400": "var(--colors-brand-400)",
          "500": "var(--colors-brand-500)",
          "600": "var(--colors-brand-600)",
          "700": "var(--colors-brand-700)",
          "800": "var(--colors-brand-800)",
          "900": "var(--colors-brand-900)",
          a10: "var(--colors-brand-a10)",
          "500-opacity": "var(--colors-brand-500-opcaity)",
        },
        sky: {
          "50": "var(--colors-sky-50)",
          "100": "var(--colors-sky-100)",
          "200": "var(--colors-sky-200)",
          "300": "var(--colors-sky-300)",
          "400": "var(--colors-sky-400)",
          "500": "var(--colors-sky-500)",
          "600": "var(--colors-sky-600)",
          "700": "var(--colors-sky-700)",
          "800": "var(--colors-sky-800)",
          "900": "var(--colors-sky-900)",
        },
        gray: {
          secondary: "var(--colors-gray-secondary)",
          "50": "var(--colors-gray-50)",
          "100": "var(--colors-gray-100)",
          "200": "var(--colors-gray-200)",
          "300": "var(--colors-gray-300)",
          "400": "var(--colors-gray-400)",
          "500": "var(--colors-gray-500)",
          "600": "var(--colors-gray-600)",
          "700": "var(--colors-gray-700)",
          "800": "var(--colors-gray-800)",
          "900": "var(--colors-gray-900)",
          a10: "var(--colors-gray-a10)",
          tertiary: "var(--colors-gray-600)",
        },
        red: {
          "50": "var(--colors-red-50)",
          "100": "var(--colors-red-100)",
          "200": "var(--colors-red-200)",
          "300": "var(--colors-red-300)",
          "400": "var(--colors-red-400)",
          "500": "var(--colors-red-500)",
          "600": "var(--colors-red-600)",
          "700": "var(--colors-red-700)",
          "800": "var(--colors-red-800)",
          "900": "var(--colors-red-900)",
        },
        yellow: {
          "50": "var(--colors-yellow-50)",
          "100": "var(--colors-yellow-100)",
          "200": "var(--colors-yellow-200)",
          "300": "var(--colors-yellow-300)",
          "400": "var(--colors-yellow-400)",
          "500": "var(--colors-yellow-500)",
          "600": "var(--colors-yellow-600)",
          "700": "var(--colors-yellow-700)",
          "800": "var(--colors-yellow-800)",
          "900": "var(--colors-yellow-900)",
        },
        green: {
          "50": "var(--colors-green-50)",
          "100": "var(--colors-green-100)",
          "200": "var(--colors-green-200)",
          "300": "var(--colors-green-300)",
          "400": "var(--colors-green-400)",
          "500": "var(--colors-green-500)",
          "600": "var(--colors-green-600)",
          "700": "var(--colors-green-700)",
          "800": "var(--colors-green-800)",
          "900": "var(--colors-green-900)",
        },
        lime: {
          "50": "var(--colors-lime-50)",
          "100": "var(--colors-lime-100)",
          "200": "var(--colors-lime-200)",
          "300": "var(--colors-lime-300)",
          "400": "var(--colors-lime-400)",
          "500": "var(--colors-lime-500)",
          "600": "var(--colors-lime-600)",
          "700": "var(--colors-lime-700)",
          "800": "var(--colors-lime-800)",
          "900": "var(--colors-lime-900)",
        },
        blue: {
          "50": "var(--colors-blue-50)",
          "100": "var(--colors-blue-100)",
          "200": "var(--colors-blue-200)",
          "300": "var(--colors-blue-300)",
          "400": "var(--colors-blue-400)",
          "500": "var(--colors-blue-500)",
          "600": "var(--colors-blue-600)",
          "700": "var(--colors-blue-700)",
          "800": "var(--colors-blue-800)",
          "900": "var(--colors-blue-900)",
        },
        white: {
          "100": "var(--colors-white-100)",
          "200": "var(--colors-white-200)",
          "300": "var(--colors-white-300)",
          "400": "var(--colors-white-400)",
          "500": "var(--colors-white-500)",
        },
      },
      fontFamily: {
        heading: "var(--font-archivo)",
        body: "var(--font-family-body)",
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
        "5xl": "var(--font-size-5xl)",
        "6xl": "var(--font-size-6xl)",
        "7xl": "var(--font-size-7xl)",
        "8xl": "var(--font-size-8xl)",
      },
      boxShadow: {
        "drop-shadow-sm": "var(--shadow-drop-shadow-sm)",
        "drop-shadow-base": "var(--shadow-drop-shadow-base)",
        "drop-shadow-md": "var(--shadow-drop-shadow-md)",
        "drop-shadow-lg": "var(--shadow-drop-shadow-lg)",
        "drop-shadow-xl": "var(--shadow-drop-shadow-xl)",
        "drop-shadow-2xl": "var(--shadow-drop-shadow-2xl)",
        "drop-shadow-inner": "var(--shadow-drop-shadow-inner)",
      },
      spacing: {
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        6: "var(--spacing-6)",
        8: "var(--spacing-8)",
        12: "var(--spacing-12)",
        16: "var(--spacing-16)",
        32: "var(--spacing-32)",
      },
      rounded: {
        base: "var(--rounded-base)",
        lg: "var(--rounded-lg)",
        xl: "var(--rounded-xl)",
        "2xl": "var(--rounded-2xl)",
        "3xl": "var(--rounded-3xl)",
        full: "var(--rounded-full)",
      },
    },
  },
  plugins: [customPlugin],
};
